### ISSUE TITLE
Feature Request: Support Object Storage resources and data sources

### ISSUE THREAD

**Issue by maylukas** [ionos-cloud/terraform-provider-ionoscloud#50]
### Current Provider Version
provider.ionoscloud v6.0.0-alpha.4

### Use-cases
* Create and manage object storage buckets & policies in Terraform

### Proposal
Implement Object storage resources & datasources similiar to the AWS provider.

### References
Resources and data sources available for provider AWS: https://registry.terraform.io/providers/hashicorp/aws/latest/docs
IONOS object storage API: https://devops.ionos.com/api/s3/#operations

Issue in predecessor provider (profitbricks): https://github.com/ionos-cloud/terraform-provider-profitbricks/issues/77

**Comment by maylukas** [comment]
I found the related issue in the now deprecated profitbricks provider (ionos-cloud/terraform-provider-profitbricks#77). In the discussion it was mentioned that this feature will be included with the next release. Is there an updated timeline?

**Comment by mflorin** [comment]
Hello @maylukas ,

We will not be implementing s3 resources and datasources since this would actually mean replicating 99% of the aws 
provider s3 code and functionality. We've submitted a pull request to the aws provider code base to allow it to work with third 
party s3 implementations that do not implement object locking and other features required by the aws provider, such is the 
case with the s3 backend used by the Ionos cloud.

The AWS PR is https://github.com/hashicorp/terraform-provider-aws/pull/17564 . However, it takes a very long time, if ever, to 
be merged.

In the meantime, you can use my branch https://github.com/mflorin/terraform-provider-aws/tree/f-aws_s3_bucket to compile
a custom aws provider, if you need s3 resources to work with the Ionos cloud.

**Comment by gthieleb** [comment]
Hi @mflorin, 

First thanks for your hard work!
After your branch was forked 8,9k and around 50.000 commits behind AWS, dont you think It's worth to be released as its own terraform provider? Is it realistic to refactor the code to align with the aws sources. What do you think are the main challenges?
